version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: library-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

  app:
    build: .
    container_name: library-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/library
    depends_on:
      - mongodb
    networks:
      - library-network
    volumes:
      - ./src:/app/src
    command: sh -c "npm install && npx nodemon --watch src src/server.js"

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge